---
- name: My first playbook
  hosts: webservers
  become: true
  tasks:
   - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install python Docker module
      pip:
        name: docker
        state: present

    - name: Downloand and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_port:80:80

     - name: Enable docker service
       systemd:
         name: docker
         enabled: yes